Repository kubernetes-sigs/cloud-provider-kind, pull requests merged in 2023-04, with the labels that each got.

#5 E2e
  .github/workflows/e2e.yml
  Makefile
  README.md
  cmd/main.go
  pkg/constants/constants.go
  pkg/controller/controller.go
  pkg/loadbalancer/server.go
  tests/tests.bats
Labels: cncf-cla: yes, approved, size/L

#3 Fix typos
  pkg/provider/instances.go
Labels: cncf-cla: yes, approved, lgtm, size/XS

#6 add install instructions
  README.md
Labels: cncf-cla: yes, approved

#8 feat: support ipv6
  go.mod
  pkg/loadbalancer/proxy.go
Labels: cncf-cla: yes, approved, size/M, lgtm
