Repository kubernetes-sigs/cloud-provider-kind, pull requests merged in 2024-09, with the labels that each got.

#127 add cloudbuild
  Makefile
  cloudbuild.yaml
  hack/init-buildx.sh
Labels: cncf-cla: yes, approved, size/M

#128 Prompt user if process running on Mac not under sudo
  cmd/app.go
Labels: cncf-cla: yes, tide/merge-method-squash, approved, lgtm, size/XS, ok-to-test

#140 Update k8s.yml
  .github/workflows/k8s.yml
Labels: cncf-cla: yes, approved, size/S
