Repository kubernetes-sigs/cloud-provider-kind, pull requests merged in 2024-04, with the labels that each got.

#36 Added name length cap for loadbalancer name
  pkg/constants/constants.go
  pkg/loadbalancer/server.go
  pkg/loadbalancer/server_test.go
Labels: cncf-cla: yes, approved, size/M, lgtm

#40 reject connections if backends are down
  .github/workflows/e2e.yml
  pkg/loadbalancer/proxy.go
Labels: cncf-cla: yes, approved, size/M, lgtm

#42 Loadbalancer for Mac
  examples/loadbalancer_multiport.yaml
  go.mod
  pkg/constants/constants.go
  pkg/container/container.go
  pkg/controller/controller.go
  pkg/loadbalancer/address_darwin.go
  pkg/loadbalancer/address_other.go
  pkg/loadbalancer/address_windows.go
  pkg/loadbalancer/server.go
  pkg/loadbalancer/server_test.go
  pkg/loadbalancer/tunnel.go
Labels: cncf-cla: yes, approved, size/L

#43 Update README.md
  README.md
Labels: cncf-cla: yes, approved, size/S

#49 Add the command to add an IP to an interface on Windows
  README.md
  pkg/loadbalancer/address_windows.go
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test
