Repository kubernetes-sigs/cloud-provider-kind, pull requests merged in 2024-06, with the labels that each got.

#56 Enable docker compose
  README.md
  compose.yml
Labels: cncf-cla: yes, approved, lgtm, size/S

#83 Use the envoy admin port to detect when the loadbalancer is ready to accept connections
  pkg/container/container.go
  pkg/loadbalancer/proxy.go
  pkg/loadbalancer/server.go
Labels: cncf-cla: yes, approved, size/M

#84 dump logs on prow
  hack/ci/e2e.sh
Labels: cncf-cla: yes, approved, size/XS

#80 Implement LoadBalancerSourceRanges
  pkg/loadbalancer/proxy.go
  pkg/loadbalancer/proxy_test.go
Labels: cncf-cla: yes, approved, lgtm, size/L

#89 avoid to restart on envoy crashes
  pkg/loadbalancer/server.go
Labels: cncf-cla: yes, approved, size/XS
