Repository kubernetes-sigs/cloud-provider-kind, pull requests merged in 2024-12, with the labels that each got.

#173 docker: cross compile binary
  Dockerfile
Labels: cncf-cla: yes, approved, lgtm, size/XS

#175 add nerdctl/finch support
  pkg/container/container.go
Labels: cncf-cla: yes, approved, size/S

#166 list the images used by cloud-provider-kind
  cmd/app.go
  pkg/images/images.go
  pkg/loadbalancer/proxy.go
  pkg/loadbalancer/server.go
Labels: cncf-cla: yes, approved, size/M, lgtm, ok-to-test

#164 Fix exclude label docs
  README.md
Labels: cncf-cla: yes, approved, size/M, lgtm, ok-to-test
