Repository kubernetes-sigs/cloud-provider-kind, pull requests merged in 2024-05, with the labels that each got.

#61 replace haproxy with envoy (static configuration)
  examples/loadbalancer_affinity.yaml
  examples/loadbalancer_udp_tcp.yaml
  pkg/container/container.go
  pkg/loadbalancer/proxy.go
  pkg/loadbalancer/proxy_test.go
Labels: cncf-cla: yes, approved, size/XL

#63 Set correct IPMode in LoadBalancerStatus
  pkg/loadbalancer/server.go
Labels: priority/important-soon, cncf-cla: yes, approved, lgtm, size/S

#67 use dynamic configuration for envoy to avoid restarting the container…
  pkg/loadbalancer/proxy.go
  pkg/loadbalancer/proxy_test.go
  pkg/loadbalancer/server.go
Labels: cncf-cla: yes, approved, size/L

#68 solve UDP crashes
  pkg/loadbalancer/proxy.go
  pkg/loadbalancer/server.go
Labels: cncf-cla: yes, approved, size/XS

#79 unit test updates
  go.mod
  go.sum
  pkg/loadbalancer/proxy_test.go
  vendor/github.com/lithammer/dedent/.travis.yml
  vendor/github.com/lithammer/dedent/LICENSE
  vendor/github.com/lithammer/dedent/README.md
  vendor/github.com/lithammer/dedent/dedent.go
  vendor/modules.txt
Labels: cncf-cla: yes, approved, lgtm, size/L
