Repository kubernetes-sigs/cloud-provider-kind, pull requests merged in 2025-01, with the labels that each got.

#187 Improve startup latency
  .github/workflows/k8s.yml
  pkg/controller/controller.go
  pkg/controller/http.go
  pkg/controller/http_test.go
Labels: cncf-cla: yes, approved, lgtm, size/L

#191 Use a shorter hash for the container name
  pkg/loadbalancer/server.go
  pkg/loadbalancer/server_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S, ok-to-test

#202 docs: describe how to use podman with kind
  README.md
Labels: cncf-cla: yes, approved, size/M, lgtm, ok-to-test

#205 If the IP is on the lo device already don't fail
  pkg/loadbalancer/address_darwin.go
  pkg/loadbalancer/address_other.go
  pkg/loadbalancer/address_windows.go
  pkg/loadbalancer/server.go
  pkg/loadbalancer/tunnel.go
Labels: cncf-cla: yes, approved, size/M, lgtm
