Repository kubernetes-sigs/cloud-provider-kind, pull requests merged in 2025-04, with the labels that each got.

#226 Update envoy to v1.33.2
  pkg/images/images.go
Labels: cncf-cla: yes, approved, lgtm, size/XS

#229 make loadbalancer tunnel protocol aware
  pkg/container/container.go
  pkg/loadbalancer/proxy.go
  pkg/loadbalancer/tunnel.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#230 add bats tests and fix udp on mac and windows
  .github/workflows/bats.yml
  .github/workflows/k8s.yml
  examples/loadbalancer_udp_tcp.yaml
  pkg/loadbalancer/tunnel.go
  tests/README.md
  tests/setup_suite.bash
  tests/tests.bats
Labels: cncf-cla: yes, approved, size/L

#238 Update k8s.yml to use go stable
  .github/workflows/k8s.yml
Labels: cncf-cla: yes, approved, size/XS

#237 Update test.yaml to go stable
  .github/workflows/test.yaml
Labels: cncf-cla: yes, approved, size/XS

#236 build with golang 1.24
  Dockerfile
Labels: cncf-cla: yes, approved, size/XS
